name: Octo Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    
jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: $default-branch
        run: echo default-branch name is $default-branch.
    
    
