name: docker image referencing

on:
  push:
    branches: [master]  

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - name: ls -al!!!!!
        run: ls -al
      
      - name: docker run test
        uses: docker://alpine:3.8
        


