
          
name: test-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: one-line script
        run: echo Hey! How have you been?
        
      - name: $default-branch
        run: echo Sometimes I miss when we are studying together. $default-branch      
