name: Upload artifact

on:
  push:
    branches: [master]
   
jobs:
  upload-output-file:

    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log
  download-output-file:
    runs-on: ubuntu-latest
    needs: upload-output-file
    steps:
      - run: echo ok!
        shell: bash


        

          
          

    

      
